# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 753a9d93a04c9205388055c3ec308c3d0669df8c4f8e7fd8040c7d8f90594da890b3f1c6a179156d93ce9662248297bb5362bb9e6b7b0756994c064f8fe7256e

test:
  secret_key_base: 89b6da342fbeaa305ded538190b502002c1285cb15e0db6d2972fc3476a7f1486ea1b7b9f93ae00135ca7911f79f38c2467dd58ea53f1024710a020d70124fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
